version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # - image: circleci/openjdk:8-jdk
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jar-{{ checksum "build.gradle" }}

      - run:
          name: Gradle version
          command: gradle --version

      - run:
          name: gradle environment
          command: gradle buildEnvironment --info --stacktrace

      - run:
          name: Install dependencies
          command: gradle dependencies --info --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jar-{{ checksum "build.gradle" }}

      - run:
          name: Runs the unit tests.
          command: gradle test --info

      - run:
          name: Generate coverage report
          command: gradle jacocoTestReport --info

      - run:
          name: upload (codecov)
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: build jar file
          command: gradle jar

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/libs
          destination: jar_files/

      - store_artifacts:
          path: build/reports/tests/test
          destination: test_report/

      - store_artifacts:
          path: build/reports/jacoco/test
          destination: coverage_report/