version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # - image: circleci/openjdk:8-jdk
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jar-{{ checksum "build.gradle" }}

      - run:
          name: Gradle version
          command: gradle --version

      - run:
          name: gradle environment
          command: gradle buildEnvironment --info --stacktrace

      - run:
          name: Install dependencies
          command: gradle dependencies --info --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jar-{{ checksum "build.gradle" }}

      - run:
          name: Runs the unit tests.
          command: gradle test --info

      # - store_test_results:
          # path: target/surefire-reports

      # - store_artifacts:
          # path: target/demo-java-spring-0.0.1-beta.1.jar

      - store_artifacts:
          path: build